### PR TITLE
Bump to v1.2.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mtrmac @vrothberg @mtrmac PTAL

**Comment by mtrmac** [comment]
LGTM. @TomSweeneyRedHat Do you happen to be around to rebase this on top of #1121? If not, no problem, I’ll merge as is after the tests finish.

**Comment by mtrmac** [comment]
Actually, we have branched `release-1.2` at the `v1.2.0` tag back in September, and landed a few new features (notably short names) as well as quite a few dependency updates.

So, should this be v1.2.1 (and we would forward the `release-1.2` branch along the main branch to this point), or v1.3, with a new `release-1.3` branch?

Paging @vrothberg @rhatdan .

**Comment by TomSweeneyRedHat** [comment]
I'm around, and I can spin a 1.3 PR later after #1121 merges.  I'll be in/out throughout today.

**Comment by mtrmac** [comment]
OK, I have merged #1121 . I don’t know that we can make the 1.2.1/1.3 branching decision today, or whether we e.g. need Jindřich for that.

I don’t have a strong opinion either way — any time this is decided, feel free to merge if tests pass.

**Comment by TomSweeneyRedHat** [comment]
OK, I'm having trouble doing the merge.  I'm going to kill this and start a new PR as I can turn that around quickly and have been looking for 15 minutes now on how to fix my merge issues.

**Pull request closed without merging**
