### PR TITLE
README: Clarify use of `libbtrfs-dev` on Ubuntu

### LINKED ISSUE #672: README: Package 'libbtrfs-dev' doesn't exist on Ubuntu < 18.10
I'm building skopeo in a container on Ubuntu 18.04 LTS, the package `libbtrfs-dev` only exists in versions 10.10 and above.

(Also at least registry to registry copying seems to work fine without it.)

### PR DESCRIPTION
**Pull request by fhemberger**
Fixes #672

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM

**Comment by fhemberger** [comment]
@vrothberg Fixed.

**Comment by rhatdan** [comment]
LGTM.
Merge once tests pass.

**Comment by vrothberg** [comment]
Merged, thanks a lot, @fhemberger!

**Pull request merged**
