### PR TITLE
CI TEST PR - add `--additional-authfile` flag

### PR DESCRIPTION
**Pull request by vrothberg**
Allow specifying additional authentication files passed through
types.SystemContext. Those additional files are only used for reading
credentials. The AuthFilePath remains the center of auth management and
is the only authentication file used for storing new and removing old
credentials.

Having the ability to specify additional authentication files can come
in handy to unify multiple entities that have dedicated auth files, for
instance, the K8s kubelet. See the below bug for additional details.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Doesn't look like you are actually doing anything with the additional auth files?
Man pages and command completions?

**Comment by vrothberg** [comment]
> Doesn't look like you are actually doing anything with the additional auth files?

We only need to pass the strings to the `SystemContext`, everything else happens in containers/image. To be honest, I was surprised by how easy it was to make the changes. Credits to @mtrmac for a really nice design of the APIs.

> Man pages and command completions?

Completions are already done but I forgot manpages entirely. Thanks for the reminder :)

**Comment by ashcrow** [comment]
Travis report:
```
2019/03/08 13:24:15 Clean vendor dir from unused packages
2019/03/08 13:24:15 	Ignoring paths matching "^github.com/containers/image/docs/.*"
2019/03/08 13:24:16 Success
2019/03/08 13:24:16 Running time: 1m29.669669514s
tree is dirty, please commit all changes and sync the vendor.conf
?? vendor/github.com/containers/image/docs/
The command "if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make vendor && ./hack/tree_status.sh && make check ; fi" exited with 1.
```

**Comment by vrothberg** [comment]
Closing as we found another solution for CRI-O.

**Pull request closed without merging**
