### PR TITLE
vendor gopkg.in/yaml.v2@v2.2.2

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: #721
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
Sure, this works. OTOH, it’s an indirect dependency of a dependency of a dependency.

Could this happen in the c/image Go module, to cause skopeo vendor to be automatically updated?

Or, I guess, even better, update c/image to use a recent version `github.com/ghodss/yaml`, which is now a Go module, and explicitly requires `gopkg.in/yaml.v2 v2.2.2`; that way there’s no magic knowledge about this package necessary in Skopeo itself.

**Comment by vrothberg** [comment]
c/image might be the better place but it has an even older version. I don't have much time to invest it further, so I am okay with merging it.
We should do some dependency house cleaning in c/image and c/storage to propagate updates more easily (and frequently).

I'll leave it up to you, @mtrmac. Feel free to close if you prefer the cleaner way.

**Comment by mtrmac** [comment]
The licensing concerns apply to all users of c/image equally, so a Skopeo-only fix is not really sufficient.

**Comment by rhatdan** [comment]
I opened https://github.com/containers/image/pull/707, does this help?

**Comment by mtrmac** [comment]
> I opened [containers/image#707](https://github.com/containers/image/pull/707), does this help?

Not with _this_ issue (YAML.v2) but upgrading github.com/imdario/mergo removes a dependency on YAML.v1 , which has the same license.  But that fix is actually more involved, see https://github.com/containers/image/pull/714 .

BTW this will be automatically resolved next time c/image is updated in skopeo after https://github.com/containers/image/pull/714 , because that updates https://github.com/stretchr/testify to v1.4.0, which pulls in the v2.2.2 version of YAML.v2.  Still, explicitly encoding that minimum version _in c/image_ might be worthwhile.

**Comment by vrothberg** [comment]
Closing. Let's get those things ironed out in c/image, where applicable. Thanks for looking into it, @mtrmac.

**Pull request closed without merging**
