### PR TITLE
WIP - Vendor storage image

### PR DESCRIPTION
**Pull request by vrothberg**
CI PR for https://github.com/containers/image/pull/601

### CODE REVIEW

**Comment by mtrmac** [comment]
ACK, please revendor c/image again.

**Comment by vrothberg** [comment]
I use this as a CI PR for https://github.com/containers/image/pull/603 now. Once that's in, I will revendor and we can merge.

**Comment by mtrmac** [comment]
@vrothberg We actually need a clean revendor from c/image master into skopeo, along with the right c/storage version, so that `make test-skopeo` in _all the other_ c/image PRs works again.

Pointing at yet another non-master branch of c/image in this PR, making it impossible to merge this PR, keeps the c/image CI broken.

**Comment by vrothberg** [comment]
> @vrothberg We actually need a clean revendor from c/image master into skopeo, along with the right c/storage version, so that make test-skopeo in all the other c/image PRs works again.
>
> Pointing at yet another non-master branch of c/image in this PR, making it impossible to merge this PR, keeps the c/image CI broken.

It makes no difference if we revendor the latest master or containers/image#603  which adds one commit on top (and is likely to be merged in the next hour).

**Comment by vrothberg** [comment]
The Travis CI doesn't start. As I stop working earlier today, I will vendor the latest commit in containers/image so we're not blocked until tomorrow.

I will open another PR for  containers/image#603 some time after.

**Comment by vrothberg** [comment]
@mtrmac CI is green.

**Comment by mtrmac** [comment]
Thanks!

**Pull request merged**
