### PR TITLE
Cirrus: Initial implementation support for GCP VMs

### LINKED ISSUE #1216: Skopeo System-testing requires Podman and/or --privileged mode
As part of https://github.com/containers/image/pull/1140 I attempted to enable skopeo's system-tests to run under a Cirrus-CI Docker-based container environment.  This fails horribly due to seccomp differences which are very difficult to resolve.  Skopeo system-testing needs to be re-implemented/updated to operate in a Docker container environment.

The only other alternative I can imagine, is to enable VM-based Cirrus-CI testing for both *skopeo* and *c/image*.  There we can freely use `--privileged` mode to run the old test design, but of course, this also enables kicking that can down the road (i.e. eventually...the tests *do* need to be modernized).

### PR DESCRIPTION
**Pull request by cevich**
Fixes #1216

Supports #1213

### CODE REVIEW

**Comment by cevich** [comment]
Ref: [VM Image keepalive tags successfully updated](https://cirrus-ci.com/task/4574806294134784?command=main#L2-L5)

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by cevich** [comment]
@lsm5 you may want to rebase your PR on this one (or after it merges).  Though don't actually create any GCP VM tasks yet, I'm still waiting on approvals and other backend bureaucratic stuffs.

**Comment by cevich** [comment]
(This PR may be merged harmlessly)

**Comment by lsm5** [comment]
@cevich great, will do. and LGTM. Just that I hit `Update Branch` which probably introduced a merge commit. That was a bad idea. Mind rebasing and force pushing please?

**Comment by cevich** [comment]
woopsie-doodle...ya, no problem.

**Comment by lsm5** [comment]
still needs a rebase likely, I still see `This branch is out-of-date with the base branch`.

**Review by lsm5 — APPROVED** [review]
LGTM.

**Comment by cevich** [comment]
I did rebase,. but I see that too...I think github hasn't caught up to reality yet.

**Comment by cevich** [comment]
huh...my remote wasn't pulling down the *actual* master HEAD for some reason.  I rebased onto the SHA and that worked :man_shrugging:

**Comment by lsm5** [comment]
Merging ...

**Pull request merged**
