### PR TITLE
install: make commands copy-pasteable

### PR DESCRIPTION
**Pull request by rhatdan**
Based on Elan Ruusamäe patch.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/skopeo/pull/1048

**Comment by TomSweeneyRedHat** [comment]
I think this is one of these "PoTAYto" vs "PoTAHto" arguments.  I fall on the other side of the fence for this change.  Regardless:
LGTM

**Comment by rhatdan** [comment]
The problem, is that we are split on both sides of the fence, and that is not a comfortable place to be.

**Comment by rhatdan** [comment]
@podman-maintainers PTAL

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by glensc** [comment]
Yay 🎉 for the merge!

I hope it takes so much effort and confirmation when the next round decides to do the exact opposite!

ps: @rhatdan you can preserve authorship with `git commit --author "$email" [--amend]`, or `git cherry-pick $commit`

**Comment by rhatdan** [comment]
@glensc Hopefully you are right.  We have many more eyes on Podman, but need to focus on all containers repos.

**Pull request merged**
