### PR TITLE
Release 1.9.2

### PR DESCRIPTION
**Pull request by mtrmac**
… primarily to sync the c/common version with Podman 4.2 (assuming it updates as well.)

- [CI:DOCS] Cirrus: Use the latest imgts container
- Cirrus: Update CI VM images to match podman CI
- Bump github.com/containers/common from 0.49.0 to 0.49.1

### CODE REVIEW

**Comment by mtrmac** [comment]
@rhatdan @vrothberg PTAL.

Cc: @lsm5

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
Thanks, https://github.com/containers/skopeo/releases/tag/v1.9.2 tagged.

**Pull request merged**
