### PR TITLE
Travis -> Cirrus: MacOS Cross test

### PR DESCRIPTION
**Pull request by cevich**
Fixes #1213

***Depends on:*** #1249

Also cleanup `Makefile` WRT `${DESTDIR}` definition and use to make it's
purpose more clear.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
Rebased.  This is ready.

**Comment by Foxboron** [comment]
Not to be that guy, but that `PREFIX` and `DESTDIR` change shouldn't have been merged.

`make PREFIX="/usr" DESTDIR="$pkgdir" install`  is how it should work, but this pull-request changes it to the more awkward `  make PREFIX="$pkgdir/usr" DESTDIR="$pkgdir" install`.

I'd like to partially revert this change patch.

Thoughts @cevich @rhatdan

**Comment by rhatdan** [comment]
I agree, I am fine with reverting that part.  We should keep this simple for the more common case and complicate it for the CI system.

**Comment by mtrmac** [comment]
> Not to be that guy, but that `PREFIX` and `DESTDIR` change shouldn't have been merged.

I have filed #1331, let’s follow up there.

**Pull request merged**
