### PR TITLE
Bump Skopeo to v1.17.0, c/common v0.61.0, c/image v5.33.0, c/storage v1.56.0

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.  In preparation of Skopeo v1.17.0 to go
out with Podman v5.3, also bump:

containers/storage:  v1.56.0
containers/image:    v5.33.0
containers/common:   v0.61.0

### CODE REVIEW

**Comment by Luap99** [comment]
Looks like we need newer CI images first as a newer golang is required.

https://github.com/containers/skopeo/pull/2456 bumps to f41 but it seems it requires changes for the new dnf5?! So maybe not straight forward but I haven't looked.

**Comment by Luap99** [comment]
Oh wait our images are fine and have the good enough go. ostree-rs-ext is a special container task using quay.io/coreos-assembler/fcos-buildroot:testing-devel and I know nothing about that and who maintains that
cc @mtrmac

**Comment by Luap99** [comment]
Git points me at https://github.com/containers/skopeo/commit/12b24fce88903e3e3d70f37320722e7b39a178dd
@TomSweeneyRedHat maybe try bumping the number there to force a rebuild to pick up a new golang.

**Comment by mtrmac** [comment]
https://github.com/containers/skopeo/pull/2460 looks promising; please follow (the manually-updated version of) https://github.com/containers/skopeo/pull/2453 , and assuming that succeeds, rebase on top.

**Comment by mtrmac** [comment]
@TomSweeneyRedHat the c/image bump in #2453 passed tests and was merged; please rebase, the test should now pass.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 @mtrmac Thanks!  Sorry about the slow turnaround, I had my head buried in other stuff.  Just rebased and repushed.

**Comment by mtrmac** [comment]
@TomSweeneyRedHat I can’t see the update on GitHub’s UI yet.

**Comment by TomSweeneyRedHat** [comment]
Well, that was more fun than anticipated. The straight rebase didn't work, though. I did learn a few new git tricks to add to my bag of tricks. I wiped out the old commits, rebased them, and did them again. I'm seeing the new commits now; the old ones are gone. They should be GTG.

**Review by Luap99 — APPROVED** [review]
LGTM

For vendor commits I never try to fix conflicts, redoing them is much simpler and faster so I agree with your drop the commits and redo them approach :)

**Review by mtrmac — COMMENTED** [review]
This looks good skimming the diff, I didn’t now check the commit structure.

I might not be around today to finish this, please review/merge and don’t wait for me.

**Comment by mtrmac** [comment]
(For vendoring rebases, my go-to approach is to edit `go.mod`, _leaving both versions in_ to resolve any conflict, and then `go mod tidy && go mod vendor`; that cleans up the duplicates in `go.mod` and overwrite the other conflicting parts.)

**Pull request merged**
