### PR TITLE
Bump to v1.15.0 and then to v1.16.0-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.  Given the changes to the c/* projects underneath Skopeo, I thought it would make sense to create a version that is using the same level of the c/* projects as Podman v5.0 and Buildah v1.35.  If this merges, I'll create a release and a release branch.

Setting main to 1.16.0-dev at the end of this.

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mtrmac @vrothberg PTAL

**Review by vrothberg — APPROVED** [review]
Changes LGTM.

I let @mtrmac merge as I am unable to follow closely the recent developments.

**Review by mtrmac — COMMENTED** [review]
Sure, tagging a release is great, code LGTM.

@TomSweeneyRedHat Do you want #2258 included or excluded? Entirely up to you.

**Comment by TomSweeneyRedHat** [comment]
@mtrmac repushed.  Thanks a bunch for pushing #2258 through.

**Review by mtrmac — APPROVED** [review]
LGTM, feel free to merge after tests pass.

Thanks!

**Pull request merged**
