### PR TITLE
Cirrus: Freshen CI images

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/automation_images/pull/82

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Thanks.

Deferring to you, please merge as appropriate.

**Comment by cevich** [comment]
> please merge as appropriate.

Okay will do.  I have parallel PRs open for buildah and podman.  I may defer merging this until those pass cleanly simply so we're using consistent images across the board.

**Comment by cevich** [comment]
The podman one is https://github.com/containers/podman/pull/10829 and is totally FUBAR (I haven't looked into it yet).

**Comment by cevich** [comment]
(rebased)

**Pull request merged**
