### PR TITLE
[release-1.3] Bump skopeo v1.3.1, c/storage v1.31.3, c/common v0.38.12

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Also includes some tweaks for the CI in this branch.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Please add an extra commit on top that bumps the version to v1.3.2-dev (and then create a tag for the previous one that says v1.3.1).

Other than that, LGTM, feel free to merge or wait for another reviewer.

**Comment by TomSweeneyRedHat** [comment]
Crud, just realized I bumped to c/common v0.38.11, needs to be 0.38.12

**Comment by TomSweeneyRedHat** [comment]
I'm going to merge this in.  I've had trouble creating tags from previous commits via the GitHub interface when working on a branch, so I'll spin up a new PR after I create the tag from this.  @mtrmac if you've some handy git tips for that, I'd appreciate hearing them.  My git knowledge is lacking in that arena.

**Comment by mtrmac** [comment]
That works.

(I usually work with `gitk --all`, IIRC finding the commit to tag, run `git tag $tag $commit`, and then `git push --tags $tag`. I haven’t tried doing this in the web UI.)

**Pull request merged**
