### PR TITLE
[WIP - DO NOT MERGE] switch to cirrus

### PR DESCRIPTION
**Pull request by lsm5**
Continuing from pr#1151

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by cevich** [comment]
@lsm5 okay, so after nearly three-weeks of tinkering, I've finally got the skopeo integration and system tests passing.  Though the situation is far from ideal.  Key things to note:

* The `setup_script` [commands to monkey-patch c/image PR code into the tests should not be used.](https://github.com/containers/image/blob/master/.cirrus.yml#L147-L156)
* The `$SKOPEO_CI_CONTAINER_FQIN` must run in `--privileged` mode for the `test-integration-local` target, but not the `test-system-local`.  This container builds automatically on quay.io for any branch change, images are tagged with the branch name.
* The privileged-container-on-a-VM situation is (hopefully temporary) **shenanigans**!  We should not be testing this way, it's broken and is hiding bugs.  Please don't hard-code this container requirement too heavily (i.e. make scripts depend on it, etc.).  i.e. I want to be able to `s/$PODMANMAKE/make/` and just run everything right on the VM.

**Comment by cevich** [comment]
Running tests outside a snowflake-container image ref: https://github.com/containers/skopeo/issues/1222

**Comment by rhatdan** [comment]
@cevich @lsm5 What is going on with this PR?

**Comment by lsm5** [comment]
> @cevich @lsm5 What is going on with this PR?

will resume it after 4.8 cycle

**Comment by cevich** [comment]
Porting the integration/system testing over from the latest c/image setup should be easy-ish.  Debugging the MacOS cross-compile + test is hard.  Ashley wasn't able to reproduce the failure on her native Mac :(

**Comment by rhatdan** [comment]
@lsm5 @cevich Any update on this?

**Comment by rhatdan** [comment]
Can we just leave the MACOS Stuff on travis for now and move all of the other testing to cirrus?

**Comment by cevich** [comment]
> Can we just leave the MACOS Stuff on travis for now

Yes, I agree this can be left for later.

**Comment by cevich** [comment]
I'm in-between Jira cards now and not enthusiastic about my next one.  So I'll take a dip here, since @lsm doesn't think it'll bother him very much: https://github.com/containers/skopeo/pull/1249

**Pull request closed without merging**
