### PR TITLE
Add Gosec GitHub Action

### PR DESCRIPTION
**Pull request by candrews**
GoSec inspects source code for security problems by scanning the Go AST.

Currently, gosec reports a number of findings that skopeo may want to address. At least with gosec as part of GitHub Actions, the skopeo project can be aware of the current state of skopeo as well the impact changes make upon it.

See: https://github.com/securego/gosec

### CODE REVIEW

**Comment by lsm5** [comment]
@candrews thanks for the PR submission. Just checking if the github action will show up as an additional task in the list? I don't see it in the checks list.

@cevich @mtrmac PTAL.

**Comment by mtrmac** [comment]
In general, I’m skeptical of “bottom-up” expansions of the CI pipeline, or adding integrations / badges just because. Let’s start with the benefit and needs of to the project, not with “this tool exists”.

Looking at `golangci-lint run --enable=gosec ./...`, this reports 5 problems, all in tests, and none of them are a security issue (even in the context of potentially exposing the user running the tests). So that’s not immediately attractive; at best we can update `WriteFile` to use `0600` instead of `0644`, for the hypothetical case of someone looking for the right way to invoke tools in our tests, and not noticing that these calls are safe in the test context.

(c/image has a similar score: 13 false positives, at best some `WriteFile` permissions in tests.

---

If we should do this, `gosec` is a vendored component of `golangci-lint`, so I think we could just enable that instead of adding a new action. (But then again, it is a linter disabled by default, as a data point…)

**Comment by cevich** [comment]
I too am against CI extensions outside of the existing cirrus-based toolchain.  Not as a tool fitment judgment, rather that it introduces "automation non-sequiturs".  For example, Renovate may suggest updates that are only tested/reflected by the cirrus jobs (or vis-versa with github-actions).  Also, github actions are a PITA to run locally.

Suggestions:
1. Can use of this tool be added as a (phony) Makefile target so developers can use it?
2. Can it be told to ignore (or skip) checking tests or test-support code?
3. Can/Should the existing (cirrus) validation check incorporate this tool, or can/should it be made a separate check (maybe even [a manually-triggered one](https://cirrus-ci.org/guide/writing-tasks/#manual-tasks))?

Note: If Cirrus-CI is/becomes a sticking point, I'm happy to help assist with resolving any issues.  Just ping me.

**Comment by mtrmac** [comment]
@cevich AFAICT we can get an equivalent set of validations by enabling a `golangci-lint` option.

---

(Overall I’m not seeing any benefit to enabling this linter, so far. That’s not to say that it could never be useful — but I am not _nearly_ enthusiastic enough to prioritize enabling it and cleaning up the code.)

**Comment by cevich** [comment]
ACK.  I could be wrong, but IIRC doesn't our current Makefile/CI usage of `golangci-lint` ignore tests?  If so, this may be a transparent addition that could prove helpful later (I dunno, I didn't look closely at tool)?

**Comment by mtrmac** [comment]
AFAIK `golangci-lint` covers everything (apart from `vendor` I think). I have confirmed that by seeing that adding a
```go
	_ = strings.Replace("a", "b", "c", 0)
```
both to `cmd/skopeo/main.go` and to `integration/sync_test.go`; `make validate-local` found that in both cases.

**Pull request closed without merging**
