### PR TITLE
docs: add MacPorts installation info

### PR DESCRIPTION
**Pull request by herbygillot**
https://ports.macports.org/port/skopeo/

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Thanks. Adding a MacPorts package would be useful.

Right now, though, at least looking at https://build.macports.org/builders/ports-11_arm64-builder/builds/88010/steps/install-port/logs/files , and comparing with the Homebrew formula, the port seems to only install a small subset of the Skopeo files that `make install` installs.

And at the very least a `policy.json` is necessary for a useful Skopeo setup; I’m not comfortable with recommending a packaging that habituates users to use `--insecure-policy` all the time.

So this seems a bit premature right now.

**Comment by herbygillot** [comment]
Understood - I will make changes to make the MacPorts port contents match what is expected.

**Comment by herbygillot** [comment]
OK, the `skopeo` port has been updated - contents are being installed by `make install`: https://build.macports.org/builders/ports-13_arm64-builder/builds/17582/steps/install-port/logs/files

It will take a while for the builders to update the archives for the other macOS versions, but the port should now be correct.

**Comment by mtrmac** [comment]
Does that work as expected? Compare https://github.com/containers/skopeo/issues/787 .

**Comment by herbygillot** [comment]
Oh that's useful - give me a few to make those modifications.

**Comment by mtrmac** [comment]
As a very minimal litmus test, I think `skopeo inspect` and `skopeo copy docker:… dir:…` needs to work out of the box.

**Pull request closed without merging**
