### PR TITLE
Accept repositories on login/logout

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now synchronize the behavior with Podman and accept repositories during login and logout per default.
#### How to verify it
Login/logout with a repository and verify `auth.json`. Push and pull should use the credentials in the same way as the Podman integration tests described in https://github.com/containers/podman/pull/11054.
#### Which issue(s) this PR fixes:

Requires https://github.com/containers/skopeo/pull/1395

#### Special notes for your reviewer:
Incorporates with https://github.com/containers/podman/pull/11054
#### Does this PR introduce a user-facing change?

```release-note
Accept repositories (and registry namespaces) on login/logout and during push/pull.
```

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Thanks!

LGTM, but please rebase to make sure this doesn’t change dependencies after the vendor dance in #1395 . (Cc: @vrothberg for a double-check.)

---

Do we want to tag a Skopeo release after this PR?

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by saschagrunert** [comment]
Rebased on top of the latest main branch.

**Review by mtrmac — APPROVED** [review]
Thanks!

**Pull request merged**
