### PR TITLE
DO NOT MERGE: Vendor in mtrmac/image:dockerd-verification

### PR DESCRIPTION
**Pull request by mtrmac**
This updates skopeo to build after https://github.com/containers/image/pull/288 .

### CODE REVIEW

**Comment by rhatdan** [comment]
Anything going on with this PR?  Needs update.

**Comment by mtrmac** [comment]
> Anything going on with this PR? Needs update.

Not too recently; I’ll update it in a batch with the others.

**Comment by rhatdan** [comment]
@mtrmac still Needs a rebase

**Comment by rhatdan** [comment]
This PR is over two years old and has not been updated in a long time.   I am going to close this, reopen if you want to update it.

**Comment by mtrmac** [comment]
I guess we don’t care about adding run-time signature verification to `docker run` any more, so I’ll close the related c/image and Jira issues as well.

**Comment by rhatdan** [comment]
Yup

**Pull request closed without merging**
