### PR TITLE
Bump containers/image to v5.4.3

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
but I'm surprised opencontainers/selinux isn't in go.mod, it is set appropriately in go.sum.  I need to learn more about go mod funkiness.

**Comment by mtrmac** [comment]
`go.mod` only contains:
- Direct dependencies
- Indirect dependencies of non-module packages
- Indirect dependencies of module packages that have been upgraded to a later version than the dependency requires

`opencontainers/selinux` is none of the above; it is an indirect dependency of modules c/image and c/storage.

**Comment by TomSweeneyRedHat** [comment]
Thx @mtrmac !

**Pull request merged**
