### PR TITLE
Add OCI artifact support, test syncing Cosign signatures again

### PR DESCRIPTION
**Pull request by mtrmac**
This is #1679 + https://github.com/containers/image/pull/1574 + #1673 .

### CODE REVIEW

**Comment by mtrmac** [comment]
This now vendors c/image from the main branch again. From a Skopeo point of view it could be merged, but we need https://github.com/containers/image/pull/1581 first so that the c/image CI doesn’t break.

**Comment by mtrmac** [comment]
Now mergeable. Note that it still vendors an unreleased c/image.

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
Ah, no bot here.

@mtrmac, could you rebase before we force merge?

**Comment by mtrmac** [comment]
Rebased.

**Pull request merged**
