### PR TITLE
add inspect layersData

### PR DESCRIPTION
**Pull request by ningmingxiao**

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks!
The code LGTM but please add a test and meaningful commit message.

**Comment by mtrmac** [comment]
Code LGTM. Thanks!

---

Hum, we don’t actually have any test of `inspect` succeeding, it seems. (There is one in system tests.) It would be nice to add one to `integration/check_test.go` — probably based on some image in `quay.io/libpod` that we would never remove? 

I don‘t personally feel strongly that adding this test should be blocking.

---

It would also be helpful to update the examples in `skopeo-inspect.1.md`. I suppose that’s not blocking either.

**Comment by mtrmac** [comment]
For reference, output format with this PR:
```console
% bin/skopeo --override-os linux inspect --no-tags docker://nginx  
{
    "Name": "docker.io/library/nginx",
    "Digest": "sha256:b95a99feebf7797479e0c5eb5ec0bdfa5d9f504bc94da550c2f58e839ea6914f",
    "RepoTags": [],
    "Created": "2022-08-23T03:59:02.789512663Z",
    "DockerVersion": "20.10.12",
    "Labels": {
        "maintainer": "NGINX Docker Maintainers \u003cdocker-maint@nginx.com\u003e"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:7a6db449b51b92eac5c81cdbd82917785343f1664b2be57b22337b0a40c5b29d",
        "sha256:ca1981974b581a41cc58598a6b51580d317ac61590be75a8a63fa479e53890da",
        "sha256:d4019c921e20447eea3c9658bd0780a7e3771641bf29b85f222ec3f54c11a84f",
        "sha256:7cb804d746d48520f1c0322fcda93249b96b4ed0bbd7f9912b2eb21bd8da6b43",
        "sha256:e7a561826262f279acf3a671b2d5684a86a8dbc48dc88e4cb65305ba4b08cae1",
        "sha256:7247f6e5c182559e2f7c010c11506802a0259958577a6e64c31b5b8f7cb0b286"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:7a6db449b51b92eac5c81cdbd82917785343f1664b2be57b22337b0a40c5b29d",
            "Size": 31381485,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:ca1981974b581a41cc58598a6b51580d317ac61590be75a8a63fa479e53890da",
            "Size": 25348180,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:d4019c921e20447eea3c9658bd0780a7e3771641bf29b85f222ec3f54c11a84f",
            "Size": 602,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:7cb804d746d48520f1c0322fcda93249b96b4ed0bbd7f9912b2eb21bd8da6b43",
            "Size": 894,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:e7a561826262f279acf3a671b2d5684a86a8dbc48dc88e4cb65305ba4b08cae1",
            "Size": 665,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:7247f6e5c182559e2f7c010c11506802a0259958577a6e64c31b5b8f7cb0b286",
            "Size": 1394,
            "Annotations": null
        }
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "NGINX_VERSION=1.23.1",
        "NJS_VERSION=0.7.6",
        "PKG_RELEASE=1~bullseye"
    ]
}
```

**Review by vrothberg — APPROVED** [review]
I am OK to merge and do some polishing after.

LGTM

**Review by mtrmac — APPROVED** [review]
> I am OK to merge and do some polishing after.

Let’s do that.

@ningmingxiao Thanks again!

**Pull request merged**
