### PR TITLE
Update an expected error message

### PR DESCRIPTION
**Pull request by mtrmac**
https://github.com/containers/image/pull/2595 will change it.

This should work with current c/image; https://github.com/containers/skopeo/pull/2441 tests whether it will work with the proposed change.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
but it looks like a rebase is needed @mtrmac

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by rhatdan — APPROVED** [review]

**Pull request merged**
