### PR TITLE
release-1.4: Introduce DISABLE_DOCS to skip doc generation while building from source

### PR DESCRIPTION
**Pull request by jaikiran**
This PR is for the 1.4.x release series and brings in the changes that were merged recently against the master branch in https://github.com/containers/skopeo/pull/1443

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@cevich, could you take a peak at the error message on this one please?  I think the CI might need some jiggling in this release branch.

**Review by lsm5 — APPROVED** [review]
LGTM.

@mtrmac @rhatdan PTAL.

@cevich I can manually merge this if the CI issue is going to be a PITA.

**Comment by lsm5** [comment]
@mtrmac Is the osx test dependent on #1446

**Comment by cevich** [comment]
Ths OSX task is not really needed on release branches IMHO, and mostly just gets in the way.  Reason: We don't actually use the build output and release branches get touched so infrequently but the MacOS VM images are constantly changing.  It's been on my TODO list to disable it, so I'll do that now since it's causing problems...

**Comment by cevich** [comment]
...fix: https://github.com/containers/skopeo/pull/1449

**Pull request merged**
