### PR TITLE
Cirrus: Update CI VM images

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
@lsm5 PTAL [epel-9 packet failure](https://dashboard.packit.dev/results/copr-builds/661705).  It seems to be complaining about a missing `go-md2man` package?

**Comment by lsm5** [comment]
> @lsm5 PTAL [epel-9 packet failure](https://dashboard.packit.dev/results/copr-builds/661705). It seems to be complaining about a missing `go-md2man` package?

/packit copr-build

**Comment by lsm5** [comment]
@cevich good to go now.

**Comment by TomSweeneyRedHat** [comment]
LGTM
but you may need a rebase.

**Review by mtrmac — APPROVED** [review]
Thanks!

**Pull request merged**
