### PR TITLE
[CI:DOCS] Github-workflow: Report both failures and errors

### PR DESCRIPTION
**Pull request by cevich**
Port of changes from https://github.com/containers/podman/pull/12997 and
https://github.com/containers/podman/pull/13005 to the workflow in this
repository.

***Note***: Impractical to automatically verify these changes until
they're merged into `main`.  Though the similar changes made in the
podman repo. have been manually confirmed to function as intended.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but it looks like you need a rebase.

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
@cevich https://github.com/containers/skopeo/actions/runs/1750812214 : Is this missing the https://github.com/containers/podman/pull/13005 part?

**Comment by cevich** [comment]
Damnit, yes :cry: Sorry I missed it.

**Comment by cevich** [comment]
Terribly sorry.  Fix is in https://github.com/containers/skopeo/pull/1549

**Pull request merged**
