### PR TITLE
build image updated to ubuntu:18.10

### LINKED ISSUE #621: recipe for target 'binary-local' failed
```
[root@iZrj9emxe3fhdrziho0mthZ skopeo-0.1.34]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

```
[root@iZrj9emxe3fhdrziho0mthZ skopeo-0.1.34]# make all
docker build  -f Dockerfile.build -t skopeobuildimage .
Sending build context to Docker daemon 14.67 MB
Step 1/4 : FROM ubuntu:17.10
 ---> e211a66937c6
Step 2/4 : RUN apt-get update && apt-get install -y     golang     btrfs-tools     git-core     libdevmapper-dev     libgpgme11-dev     go-md2man     libglib2.0-dev     libostree-dev
 ---> Using cache
 ---> add8c6365bab
Step 3/4 : ENV GOPATH /
 ---> Using cache
 ---> 85edf1bac744
Step 4/4 : WORKDIR /src/github.com/containers/skopeo
 ---> Using cache
 ---> cc41e10a9642
Successfully built cc41e10a9642
docker run --rm --security-opt label=disable -v $(pwd):/src/github.com/containers/skopeo \
	skopeobuildimage make binary-local  BUILDTAGS='btrfs_noversion libdm_no_deferred_remove '
go build "-buildmode=pie" -ldflags "-X main.gitCommit=" -gcflags "" -tags "btrfs_noversion libdm_no_deferred_remove " -o skopeo ./cmd/skopeo
vendor/github.com/klauspost/compress/flate/inflate.go:13:2: cannot find package "math/bits" in any of:
	/src/github.com/containers/skopeo/vendor/math/bits (vendor tree)
	/usr/lib/go-1.8/src/math/bits (from $GOROOT)
	/src/math/bits (from $GOPATH)
Makefile:83: recipe for target 'binary-local' failed
make: *** [binary-local] Error 1
make: *** [binary] Error 2
```

### PR DESCRIPTION
**Pull request by hakandilek**
fixes #621

### CODE REVIEW

**Comment by vrothberg** [comment]
Hi @hakandilek, thanks a lot for contributing!

Would you sign the commit (e.g., `git commit --amend -s`)? Note that the commit does not fix #621, which refers to building the image locally. The problem of 621 is that it's using go 1.8 which we don't support anymore.

**Comment by vrothberg** [comment]
> Note that the commit does not fix #621, which refers to building the image locally. The problem of 621 is that it's using go 1.8 which we don't support anymore.

Sorry, it actually does. The example in #621 actually builds in the container.

**Comment by hakandilek** [comment]
> Sorry, it actually does. The example in #621 actually builds in the container.

yes ubuntu 18.10 delivers go 1.10 as default golang package:
https://packages.ubuntu.com/cosmic/golang

if you prefer, I can also update the script to install 1.12.

**Comment by rhatdan** [comment]
@hakandilek Could you squash your commits together.

git rebase -i origin
And use the fixup flags.

**Pull request merged**
