### PR TITLE
Update to F34beta images + add hack/get_ci_vm.sh script

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
@lsm5 FYI - having this PR merged may be helpful to you.  The hack script can be used on non-commited `.cirrus.yml` (or any) changes to test them :grin:

**Comment by lsm5** [comment]
> @lsm5 FYI - having this PR merged may be helpful to you. The hack script can be used on non-commited `.cirrus.yml` (or any) changes to test them grin

how exactly would that be run? Would a Makefile target makes things easy?

**Comment by cevich** [comment]
> how exactly would that be run? Would a Makefile target make things easy?

The new script consumes `.cirrus.yml` directly, so you simply `hack/get_ci_vm.sh --list` to get the names, then `hack/get_ci_vm.sh <cirrus task name>`.  It only works with VM-based tasks, not containers (yet).

Nothing need be committed or pushed. So for example you can add a `test_foobar_task` to `.cirrus.yml` and then run `hack/get_ci_vm.sh test_foobar` to test it out.

**Comment by cevich** [comment]
This is ready.  The travis failure is just a "docker hub rate-limit exceeded" failure :confounded:

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
