### PR TITLE
use fedora:latest in contrib/skopeoimage/*/Dockerfile

### PR DESCRIPTION
**Pull request by lsm5**
Fixes: #1492

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@vrothberg @mtrmac @rhatdan @TomSweeneyRedHat @cevich PTAL

### CODE REVIEW

**Comment by cevich** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I thought there had been a reason for having a version specified, but I'm not finding it in the history, so LGTM!

**Comment by TomSweeneyRedHat** [comment]
LGTM
maybe CI didn't like the exclamation

**Comment by lsm5** [comment]
ya we don't have openshift bot in here, so /commands probably won't work. thanks all

**Pull request merged**
