### PR TITLE
Vendor in latest containers/storage and containers/image

### PR DESCRIPTION
**Pull request by rhatdan**
Update containers/storage and containers/image to define location of local storage.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe PTAL,  I am trying to get skopeo to work when running as non root to pull content out of the users store.

It looks like skopeo needs to enter the user namespace to be allowed to do the copy.

 ./skopeo copy containers-storage:alpine dir:/tmp/alpine
FATA[0000] Invalid source name containers-storage:alpine: chown /home/dwalsh/.local/share/containers/storage/overlay/l: operation not permitted

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Comment by mtrmac** [comment]
@rhatdan ACK.  Please rebase on top of c/image master, until we merge this all other c/image PRs will fail tests.

**Comment by vrothberg** [comment]
@rhatdan, can you update the `vendor.conf` and let it point to the regular projects? Once that's merged, the CI over at containers/image will pass again.

**Comment by rhatdan** [comment]
@vrothberg @mtrmac Updated.  Ready to merge?

**Comment by vrothberg** [comment]
LGTM, let's do this :)

**Pull request merged**
