### PR TITLE
CONTRIBUTING: update vendoring instructions

### PR DESCRIPTION
**Pull request by moio**
:wave: skopeo maintainers!

This updates the contribution instructions to use go modules vendoring instead of `vndr`.

I hope I interpreted the intention correctly as I stumbled into this while trying to open my first PR (trying to do that according to documentation!).

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Thanks!

Everything in this PR looks correct; since you are working in this area (and are looking at it with fresh eyes), would you care to change the instructions further to use the Go tools? I think that’s `go get`, `go get -u`, and more importantly `go mod edit -replace` and `go mod edit -dropreplace`; in particular, IIRC `go mod edit -replace …=…@latest` would automatically figure out the right date/commit number so that it doesn’t have to be computed manually.

**Comment by moio** [comment]
Thanks @mtrmac, all good points. I hope the text is OK now!

**Comment by rhatdan** [comment]
Could you squash your commits.

**Comment by moio** [comment]
> Could you squash your commits.

Done

**Review by mtrmac — APPROVED** [review]
Thanks again!

**Pull request merged**
