### PR TITLE
[release-1.11] Bump to v1.11.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.  To ready for RHEL 8.8/9.2

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by mtrmac** [comment]
Thanks!

Could you add another commit to update to 1.11.2-dev on top, please?

**Comment by mtrmac** [comment]
Thanks! Sorry for the delay.

**Comment by mtrmac** [comment]
https://github.com/containers/skopeo/releases/tag/v1.11.1 is published.

Cc: @jnovy

**Comment by TomSweeneyRedHat** [comment]
TY @mtrmac !

**Pull request merged**
