### PR TITLE
[release-1.9] 1.9 backports

### PR DESCRIPTION
**Pull request by mtrmac**
Just https://github.com/containers/image/pull/1695 + tagging 1.9.3.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
needed for RHEL 8.7.0ZeroDay to be created from https://bugzilla.redhat.com/show_bug.cgi?id=2135973

**Comment by mtrmac** [comment]
Podman has a test failure, investigating…

**Comment by mtrmac** [comment]
Oh well, Podman passed on a re-run.

**Pull request merged**
