### PR TITLE
[release-1.4] Cirrus: Drop OSX task

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/skopeo/pull/1850

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
I’d weakly prefer to keep `cross_task` enabled, but let’s discuss that in #1850 and follow the outcome here.

**Comment by cevich** [comment]
> I’d weakly prefer

Np.  I'll put it back in.

**Comment by cevich** [comment]
Okay, I think this is ready to go now.

**Review by mtrmac — APPROVED** [review]
Thanks!

**Pull request merged**
