### PR TITLE
vendor: don't remove containers/image/registries.conf

### PR DESCRIPTION
**Pull request by vrothberg**
Instruct vndr to not remove image/registries.conf to ease packaging on
Ubuntu.

Fixes: #618
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
@rhatdan @mtrmac can we get this merged please?

**Comment by vrothberg** [comment]
Just updated. Once CI is green, we can merge. It doesn't hurt us and we're already whitelisting the manpages.

**Comment by mtrmac** [comment]
LGTM

**Comment by mtrmac** [comment]
Actually, merged #616 first, and the tests on this one haven’t started yet; can you rebase, please?

**Comment by vrothberg** [comment]
done :heavy_check_mark:

**Comment by vrothberg** [comment]
@rhatdan @mtrmac I don't understand why Travis does not kick off in Skopeo. I suspect some (project) config issue as the jobs start much sooner for other projects.

**Comment by vrothberg** [comment]
@lsm5, you're good to go.

**Pull request merged**
