### PR TITLE
[CI:DOCS] install.md: remove Kubic package info for Ubuntu

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@TomSweeneyRedHat @vrothberg @mtrmac @rhatdan PTAL

### CODE REVIEW

**Review by mtrmac — APPROVED** [review]

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
Thanks!

**Comment by felipecrs** [comment]
Is there any reference on why this was removed? It seems that skopeo is also missing from the Kubic repo.

This broke countless Dockerfiles I had, unfortunately.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 could you add a quick explainer please?

**Comment by mtrmac** [comment]
#1648 has more of the conversation now.

**Pull request merged**
