### PR TITLE
Add timeouts when waiting on OpenShift or the registry to start

### PR DESCRIPTION
**Pull request by mtrmac**
… so that we terminate with the full context and pointing at the relevant code, instead of relying on the overall test suite timeout.

### CODE REVIEW

**Comment by mtrmac** [comment]
Failure starting OpenShift looks like this:
```
FAIL: sync_test.go:46: SyncSuite.SetUpSuite

Waiting for master
Checking for port 8443...
Sleeping for port 8443
sync_test.go:60:
    s.cluster = startOpenshiftCluster(c) // FIXME: Set up TLS for the docker registry port instead of using "--tls-verify=false" all over the place.
openshift.go:128:
    c.Fatalf("Timed out waiting for master: %v", ctx.Err())
... Error: Timed out waiting for master: context deadline exceeded

Terminating log check
Terminating port check
Check for port 8443 terminated
Port checker for port 8443 exiting
```

**Comment by mtrmac** [comment]
Failure starting the registry looks like this
```
----------------------------------------------------------------------
FAIL: copy_test.go:44: CopySuite.SetUpSuite

… lots of OpenShift start-up logs …
copy_test.go:49:
    s.cluster = startOpenshiftCluster(c) // FIXME: Set up TLS for the docker registry port instead of using "--tls-verify=false" all over the place.
openshift.go:180:
    c.Fatalf("Timed out waiting for registry to start: %v", ctx.Err())
... Error: Timed out waiting for registry to start: context deadline exceeded
Check for port 5000 terminated
Port checker for port 5000 exiting
----------------------------------------------------------------------
```

though the way it works now, we don’t tear down the cluster on failure, so another suite may fail trying to start OpenShift. Still, that should be an improvement over hanging.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
