### PR TITLE
WIP - detect copy operations by other processes

### PR DESCRIPTION
**Pull request by vrothberg**
https://github.com/containers/image/pull/607 and https://github.com/containers/storage/pull/307 must be merged before this PR.

Requires to vendor containers/image, storage and the latest
version of the progress bar library.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Here's an example how to test it:
https://asciinema.org/a/YKk9jm9s8Hivi5JVTCM4SX7q4

**Comment by edsantiago** [comment]
I'm obviously doing something wrong; I can't get my skopeo to recognize a simultaneous pull:
```
$ git show
commit dd70b2a9f846f45f4381d45d4df36e7d77d4db9c (HEAD -> pr/619)
...
$ make binary-local
go build "-buildmode=pie" -ldflags "-X main.gitCommit=dd70b2a9f846f45f4381d45d4df36e7d77d4db9c" -gcflags "" -tags "   ostree " -o skopeo ./cmd/skopeo
$ sudo ./skopeo copy docker://fedora:29 containers-storage:fedora:esm1   [and, in other window, esm2]
```
In all my attempts, both skopeos pull the entirety of `01eb078129a0`. Do you see any obvious problems with my setup?

**Comment by vrothberg** [comment]
@edsantiago my apologies! As @mtrmac pointed out here https://github.com/containers/image/pull/607#discussion_r267524986, it's the code not you. I simply missed committing the last s/false/true/ to the PR at containers/image. Sorry! I shouldn't commit at the end of the day :hear_no_evil:

**Comment by edsantiago** [comment]
That works better, thank you! 

The word 'stopped' is pretty strong; would you consider 'paused' instead? And perhaps '*being* copied' to indicate ongoing activity?

**Comment by vrothberg** [comment]
> That works better, thank you!
> 
> The word 'stopped' is pretty strong; would you consider 'paused' instead? And perhaps '_being_ copied' to indicate ongoing activity?

Sounds great, thanks!

**Comment by vrothberg** [comment]
@rhatdan @mtrmac @nalind @edsantiago, please have another look:
- storage: https://github.com/containers/storage/pull/307
- image: https://github.com/containers/image/pull/607

Besides several cleanups of the code, I performed the following changes:
- Storage does not expose digest-specific Lock() - Unlock() API anymore but has a `GetDigestLock(path string) (Locker, error)` API that we use in `storageImageDestination`.
- File descriptors do not leak anymore as the lock files are now opened and closed on demand. We're already reference counting in the lockfile implementation. When Unlocking the last remaining reference on a lock we're closing the file descriptor.
- The digest locks are being tracked in `storageImageDestination` and all locked locks (but not yet unlocked ones) are unlocked in `storageImageDestination.Close()` which is being invoked in a deferred call in `copy.Image()` and effectively avoids deadlocks in the precense of errors or panics.

**Comment by vrothberg** [comment]
Closing in favour of https://github.com/containers/image/pull/611.

**Pull request closed without merging**
