### PR TITLE
Embed default-policy into binary

### PR DESCRIPTION
**Pull request by felipecrs**
This should make the usage of the skopeo statically linked binary a lot simpler.

- Refs https://github.com/containers/skopeo/issues/1648#issuecomment-1580905503

### CODE REVIEW

**Comment by felipecrs** [comment]
I tested it, and it works nice.

**Comment by felipecrs** [comment]
The build errors doesn't seem related:

```
RPM build errors:
    source_date_epoch_from_changelog set but %changelog is missing
    File not found: /builddir/build/BUILDROOT/skopeo-1.12.1~dev-1.20230607224542237766.pr2014.36.gfb180f03.fc39.aarch64/usr/share/man/man1/%{name}*
Finish: rpmbuild skopeo-1.12.1~dev-1.20230607224542237766.pr2014.36.gfb180f03.fc39.src.rpm
```

**Comment by felipecrs** [comment]
How about hide this "feature" behind a compile flag, so that only users building the static binary can set it?

**Comment by mtrmac** [comment]
A static binary having a different security behavior from a dynamic one would be an even more risky footgun.

**Comment by mtrmac** [comment]
Also consider the supply chain security risks of individually distributed static binaries.

Distribution packages really are strongly recommended over that, for many reasons.

Alternatively there is https://github.com/containers/skopeo/tree/main/contrib/skopeoimage .

**Comment by mtrmac** [comment]
My opinion on static binaries is not nearly as strong as my opinion that the security enforcing code needs to be paranoid about both bugs and human operators’ mistakes.

E.g. users could intend to ship a config file by something like Ansible, but make a typo in the path. Or a mount command could fail.

**Comment by felipecrs** [comment]
I understand. That makes sense.

**Comment by mtrmac** [comment]
Of course users are free to patch their own systems, or to wrap Skopeo in a shell script that always adds `--insecure-policy`.

And ignoring signatures may well be the right call for some environments.

I just don’t think it’s the right trade-off for wide distribution.

**Pull request closed without merging**
