### PR TITLE
Vendor latest github.com/containers/storage

### PR DESCRIPTION
**Pull request by nalind**
Update github.com/containers/storage to master(be846769b4977f3ae0c0256d50827440e72fc0b0).  This is largely about getting the changes from https://github.com/containers/storage/pull/283 here so that when we introduce a patch to containers/image that depends on the newer fields that PR introduced, its tests will pass.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, although we should probably move to a new release of containers/storage.

**Comment by nalind** [comment]
Hmm, I think we're going to need https://github.com/containers/storage/pull/284, too.

**Comment by nalind** [comment]
Updated to 06b6c2e4cf254f5922a79da058c94ac2a65bb92f.

**Comment by mtrmac** [comment]
LGTM pending tests. Thanks!

**Pull request merged**
