### PR TITLE
update c/image

### PR DESCRIPTION
**Pull request by vrothberg**
* progress bar: use spinners for unknown blob sizes
 * improve README.md and the review of the changes
 * use 'containers_image_ostree' as build tag
 * ostree: default is no OStree support
 * Add "Env" to ImageInspectInfo
 * config.go: improve debug message
 * config.go: log where credentials come from

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

Don't merge until https://github.com/containers/image/pull/657 is in and this PR is revendored.

### CODE REVIEW

**Comment by vrothberg** [comment]
Ready for merging. @rhatdan @TomSweeneyRedHat @edsantiago @mtrmac PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
I don't understand the `improve README.md` item in the commit message - I see no such corresponding diff (I do for the rest). I would assume you grabbed that from commit logs and the README itself isn't important for this commit, so the easiest change is to remove it from the commit message?

Otherwise LGTM

**Comment by vrothberg** [comment]
@edsantiago, that's the README from c/image which isn't pulled in. I basically just created a changelog from the previously vendored version to the new one.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
