### PR TITLE
020-copy.bats: check that we set the manifest type correctly

### PR DESCRIPTION
**Pull request by nalind**
When copying to an OCI layout destination, forcing zstd compression, check that the manifest correctly describes the type of the layer blob.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Tests are still angry @nalind

**Comment by nalind** [comment]
That's intentional - the new bits of the test add a case that https://github.com/containers/image/pull/1089 is expected to fix.

**Comment by mtrmac** [comment]
@nalind do you want to update this now, or only after a c/image release? (Or maybe there should be a release straight away?)

**Comment by nalind** [comment]
I know you've got some things that you want to merge soonish, and this PR can wait until there's a tagged release.  I was manually running this test scenario before pushing updates to https://github.com/containers/image/pull/1089, so I don't expect any problems here.

A new tag will get picked up by various dependabot instances when it runs over the coming weekend, so my preference would be to have a tagged release before then.  OpenShift also prefers to use a tag rather than a commit ID, for example [in OKD](https://github.com/openshift/okd/issues/402#issuecomment-762369650), but I can try to `go mod replace` to a commit ID if you're not planning to tag a release soon.

**Review by mtrmac — APPROVED** [review]
LGTM. Thanks!

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
