### PR TITLE
Bump to v1.2.0

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg I would like to cut a new release.

**Comment by rhatdan** [comment]
Here is the changelog:

```
    -buildmode=pie is not supported for some arch
    A couple of minor code cleanups.
    Add --registry-token flags to support Bearer token authentication
    Add --registry-token tests to utils_tests.go
    Add an extra clarification to skopeo-copy(1)
    Add an extra clarification to skopeo-copy(1)
    Add oci-archive to transport list, and link to the authoritative man page
    Adding periods
    Build static binary with `buildGoModule`
    Bump github.com/containers/common from 0.14.0 to 0.22.0
    Bump github.com/containers/image/v5 from 5.5.1 to 5.6.0
    Bump github.com/containers/ocicrypt from 1.0.2 to 1.0.3
    Bump github.com/containers/storage from 1.21.1 to 1.23.5
    Cleanup Dockerfile builds
    Dockerfile.build: Upgrade to Ubuntu 20.04
    Fix macOS builds in Travis
    Fix make clean to actually remove binaries
    Fix problems found by codespell
    Fix skopeo-login docs typo
    Keep options order in code and add missing bash completions
    Make InspectOutput an external object
    Remove an obsolete documentation of (make binary-static)
    Retry on skopeo subcommands
    Retry skopeo inspect command
    Run htpasswd from our build-container instead of registry:2
    Switch containers/libpod->containers/podman
    Update nix pin with `make nixpkgs`
    Use an inter-registry copy as the example for (skopeo copy)
    Use c/common retry package
    fix build in docker container
    nix run -f channel:nixos-20.03
    update enc/dec docs to be consistent with buildah
    use base image golang for build
    vendor golang.org/x/text@v0.3.3
```

**Review by vrothberg — COMMENTED** [review]
LGTM

Let's wait for a head nod from @mtrmac

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by mtrmac** [comment]
ACK, I don’t think there’s any urgent work in progress we need to wait for.

**Pull request merged**
