### PR TITLE
V1.2.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

### CODE REVIEW

**Comment by mtrmac** [comment]
Implementation LGTM. Version number was discussed in #1154 .

**Comment by vrothberg** [comment]
I think this should be against the `release-1.2` branch.

**Comment by mtrmac** [comment]
@vrothberg Do you mean that this exactly this PR (full contents of of the `master` branch to this point) should be included on the `release-1.2` branch, or that there should be a 1.2.1 release from the `release-1.2` branch (and if so, what should it contain? that branch is exactly at the 1.2.0 tag currently).

**Comment by vrothberg** [comment]
> @vrothberg Do you mean that this exactly this PR (full contents of of the `master` branch to this point) should be included on the `release-1.2` branch, or that there should be a 1.2.1 release from the `release-1.2` branch (and if so, what should it contain? that branch is exactly at the 1.2.0 tag currently).

A bit of everything I guess. Tagging 1.2.1 on the release-1.2 branch would imply cherry-picking all commits from master that went in after the branch.

**Comment by jnovy** [comment]
@vrothberg assuming the new release of skopeo-1.2.1 will be created off master and then we decide if we want to rebase release-1.2 to it? Meaning after release of skopeo-1.2.1? This menas nothing blocks us to release 1.2.1 now?

**Comment by mtrmac** [comment]
For the record:
- Releasing as 1.2.1 because a 1.2.x was planned
- Forwarding the `release-1.2` branch to this point
- The `release-1.2` branch is intended to be stable / slow-moving from now on.

**Pull request merged**
