### PR TITLE
Switch to github.com/etcd-io/bbolt

### PR DESCRIPTION
**Pull request by vrothberg**
github.com/boltdb/bolt is no longer maintained.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Do not merge. This is vendoring a private fork to be sure we don't hit a regression before opening a PR for c/image.

**Comment by vrothberg** [comment]
The c/image PR has been merged, and I vendor the main repo again, so we're good to go.

@rhatdan @TomSweeneyRedHat @mtrmac PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by rhatdan** [comment]
LGTM
@mtrmac @giuseppe @TomSweeneyRedHat @mheon PTAL

**Comment by mheon** [comment]
LGTM

**Pull request merged**
