### PR TITLE
Bump to v0.2.0

### LINKED ISSUE #276: Can not list Tags on Repo when there is no latest tag
When i'm trying to list tags on specific repo, i got this error message :

- Erreur : manifest unknown: manifest unknown

Thanks

### PR DESCRIPTION
**Pull request by rhatdan**
Update on #834: force runc only when cgroupsv1
    Update docs/skopeo.1.md
    Add example with repository
    Skopeo should support for BigFilesTemporaryDir (SystemContext)
    Use fully-qualified image names
    Mention CentOS/RHEL in installation instructions
    bump to a supported ubuntu release
    add support for REGISTRY_AUTH_FILE
    Partial image encryption support
    Fix wrong import of docker reference
    Fix inconsistency in manpage example for list-tags
    Fix formatting on test
    Adds "list-tags" command to list tags with no known tag required. Fixes #276

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg @TomSweeneyRedHat PTAL

**Comment by mtrmac** [comment]
- This needs to wait until the versions of all dependencies are settled
- … and then it needs to be rebased on top of all the dependency updates, so that the tag includes them.

**Comment by vrothberg** [comment]
Yes, please wait until we have c/image, c/storage and c/common aligned in Podman, Buildah and Skopeo.

**Comment by vrothberg** [comment]
https://github.com/containers/skopeo/pull/887 for c/image

**Comment by rhatdan** [comment]
Rebased on latest code.  We are close on release.  I guess we wait until Buildah and Podman are ready.

**Pull request merged**
