### PR TITLE
Test new removal of error and Error from error messages

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Review by mtrmac — COMMENTED** [review]
Sure, the test update is fine.

Let’s discuss the changes in https://github.com/containers/image/pull/1240 only.

**Comment by mtrmac** [comment]
@rhatdan #1356 is this+`make vendor`, seems to pass at least the `validate` step.

**Comment by mtrmac** [comment]
Merged #1356 instead (just an one-line update to `go.sum` on top of this one). Thanks!

**Pull request closed without merging**
