### PR TITLE
Update storage manpage from c/storage

### PR DESCRIPTION
**Pull request by rwha**
This manpage has had a few updates from containers/storage. Is that project integrated into skopeo in some way that possibly misses this file? If so please let me know and I will make the appropriate change.

Signed-off-by: Ryan Whalen <rj.whalen@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Not sure why this file is here, since it is also stored in
https://github.com/containers/storage/blob/master/docs/containers-storage.conf.5.md

I know in Fedora we assemble the content from each different containers repo and ship the man pages together in containers-common.

Anyways LGTM

**Comment by TomSweeneyRedHat** [comment]
Ditto @rhatdan.  The changes look good, but if all possible I'd like to remove this file from skopeo and just use the one in containers/storage.  @lsm5 @mtrmac @vrothberg is this possible?

**Comment by mtrmac** [comment]
The file was added for @lsm5 , let’s wait for him.

**Comment by rhatdan** [comment]
Lets remove the file and rely on containers/storage.  Eventually we should just move it to containers/common.

**Comment by rhatdan** [comment]
I am just going to remove these files.
Thanks @rwha

**Pull request closed without merging**
