### PR TITLE
[hack/libdm_tag.sh] Fix failed build in absence of libdevmapper.h

### PR DESCRIPTION
**Pull request by rahilarious**

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Thanks for the PR.

This would re-purpose an existing check for an entirely different thing (If `exclude…` were used, the `no_deferred_remove` build tag should make no difference anyway).

---

@giuseppe @baude Is there some other consensus on device-mapper support? AFAICT it was hard-coded disabled for Podman in https://github.com/containers/podman/commit/407354198169f33a1ebebca3ae47d5d0c34d9b42 back in 2018, and in Buildah in https://github.com/containers/buildah/pull/4832 this year.

Should Skopeo follow suit and hardcode disabling it as well?

**Comment by rahilarious** [comment]
> This would re-purpose an existing check for an entirely different thing (If `exclude…` were used, the `no_deferred_remove` build tag should make no difference anyway).

Yeah it makes other tag redundant
>  
> Should Skopeo follow suit and hardcode disabling it as well?

+1

**Comment by giuseppe** [comment]
> @giuseppe @baude Is there some other consensus on device-mapper support? AFAICT it was hard-coded disabled for Podman in [containers/podman@4073541](https://github.com/containers/podman/commit/407354198169f33a1ebebca3ae47d5d0c34d9b42) back in 2018, and in Buildah in [containers/buildah#4832](https://github.com/containers/buildah/pull/4832) this year.
> 
> Should Skopeo follow suit and hardcode disabling it as well?

IMO yes, let's disable it, there is no reason (beside being stuck on RHEL 7) to use that backend.

**Comment by mtrmac** [comment]
#2283 proposes hard-coding the driver to disabled.

**Comment by mtrmac** [comment]
#2283 was merged. Thanks for initiating this!

**Pull request closed without merging**
