### PR TITLE
Update for https://github.com/containers/image/pull/1299

### PR DESCRIPTION
**Pull request by mtrmac**
This updates expected test output for https://github.com/containers/image/pull/1299 .
<s>Still outstanding: Figure out what kinds of “list tags” failures we care about, and how to detect that.</s>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac Shouldn't this be closed?

**Comment by mtrmac** [comment]
Fixes #1230 (old/new):
```console
% c inspect --override-os linux docker://public.ecr.aws/nginx/nginx:latest        
FATA[0004] Error determining repository tags: fetching tags list: invalid status code from registry 404 (Not Found) 

WARN[0003] Registry disallows tag list retrieval; skipping 
{
…
```

**Comment by mtrmac** [comment]
This is now ready for review.

⚠️ Note the individual commits that deal with workarounds:
- Dropping the special case in `skopeo sync`
- Dropping an IBM BlueMix workaround
- Replacing an AWS workaround with untested code
- Adding a new AWS workaround (this one is tested, and has the response recorded)

I _hope_ that the changes are correct, and it’s probably the best I can do right now, but “hope” is not the usual standard of safety we aspire to.

**Comment by mtrmac** [comment]
Merging now, so that c/image and Skopeo CI is not broken for other work.

**Pull request merged**
