### PR TITLE
[release-1.2] Bump prometheus/client_golang to 1.11.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

This addresses https://issues.redhat.com/browse/RHEL-13436

[NO NEW TESTS NEEDED]
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg PTAL.  I'm always a doubting Thomas when doing indirect vendors.  This tries to emulate @lsm5 's https://github.com/containers/skopeo/commit/3bc062423eb5e8c538379338e9a7b9af77a4a549 

This also dragged in more than I had anticipated.

**Comment by mtrmac** [comment]
@TomSweeneyRedHat See the restricted comment in https://issues.redhat.com/browse/RHEL-13436 ; and compare discussion in #1605 .

If this needs to happen anyway, from a quick spot check this looks plausible. Perhaps a `go mod tidy` might trim the diff by a few lines, but that doesn’t really matter.

**Comment by mtrmac** [comment]
(Note to self: CI doesn’t run on this branch, and I didn’t even try compiling it.)

**Comment by TomSweeneyRedHat** [comment]
@mtrmac thanks for the thorough analysis in the Jira card.  Given that, and the fact that I don't like to play with matches unecessarily, I'm closing this.

**Pull request closed without merging**
