### PR TITLE
vendor: Bump golang.org/x/net to 4.0

### PR DESCRIPTION
**Pull request by cgwalters**
I originally thought I needed this to fix a build, but that was apparently not the case.

Signed-off-by: Colin Walters <walters@verbum.org>

### CODE REVIEW

**Comment by cgwalters** [comment]
Build of current main with 1.19:

```
$ make
GO111MODULE=on go build -mod=vendor "-buildmode=pie" -ldflags '-X main.gitCommit=e024c4389257abb3c6f2d28c0612ca55e9e58a75 ' -gcflags "" -tags "   " -o bin/skopeo ./cmd/skopeo
# golang.org/x/net/http2/hpack
vendor/golang.org/x/net/http2/hpack/tables.go:129:5: staticTable redeclared in this block
        vendor/golang.org/x/net/http2/hpack/static_table.go:6:5: other declaration of staticTable
make: *** [Makefile:142: bin/skopeo] Error 2
```

**Comment by mtrmac** [comment]
Hum, the current version builds fine for me (macOS 13.0.1, `go version go1.19.4 darwin/amd64`). Notably `static_table.go` is not a part of the repo at all yet (it was only added to `x/net` on in https://github.com/golang/net/commit/84c13af5f4449b859ebfa62d481cce07fedf6da4 , which later than the version in `go.mod`).

Is it possible you had that file left around locally?

On the contrary, the PR is failing because `static_table.go` was not added.

(I don’t mind doing the update anyway, fresher versions of dependencies on the main branch are good by default — but I want to make sure the cause of the build breakage is understood to avoid surprises.)

**Comment by cgwalters** [comment]
Ahh, weird.  I am not entirely sure what happened here.  I think something modified my `go.mod` or `go.sum` (maybe IDE tooling) and then I tried to fix things and indeed somehow corrupted that.

Regardless, I've verified you're right that things build on main.  But this PR bumps the dependency anyways.

**Review by mtrmac — APPROVED** [review]
LGTM.

**Pull request merged**
