### PR TITLE
Bump to v1.0.0

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
WOOT!
LGTM
I think we ought to let @mtrmac have the honor of merging this one. Nice work All!

**Comment by TomSweeneyRedHat** [comment]
Hate to ask, but should this be respun to get the man page PR that just went in?

**Comment by rhatdan** [comment]
Well that is a minor change, but I will let @mtrmac decide.

**Comment by mtrmac** [comment]
But I think having the `login`/`logout` references in the man page would be useful when it’s one of the major new features of this release.

But if we are in a hurry, it’s not critical.

**Comment by rhatdan** [comment]
Ok lets get the Man page/README fix in and then I will rebase on Monday.  But we do want to get this out by Monday.

**Pull request merged**
