### PR TITLE
Test github.com/mtrmac/image:mirror-reference

### PR DESCRIPTION
**Pull request by mtrmac**
<s>DO NOT MERGE: This uses unmerged https://github.com/containers/image/pull/912</s>

Vendor in https://github.com/containers/image/pull/912 , and add tests that we are enforcing the correct identities when accessing images through mirrors.

### CODE REVIEW

**Comment by mtrmac** [comment]
Re-vendored from merged https://github.com/containers/image/pull/912 .  This will cause Skopeo to use an unreleased version of c/image, but I think it’s important to have this test added and enforcing as soon as possible (even if we released c/image within a few days).

**Comment by rhatdan** [comment]
LGTM
@vrothberg PTAL

**Comment by rhatdan** [comment]
@vrothberg Reping

**Comment by mtrmac** [comment]
Rebased, tests pass.

**Pull request merged**
