### PR TITLE
install: No more Debian Testing/Unstable/Sid repos, remove them

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@lsm5 WDYT?
Tests are all kinds of unhappy, looks like a flake.

**Review by lsm5 — CHANGES_REQUESTED** [review]
I think we should let people know where to get skopeo if they are on debian testing or sid or ubuntu >= 20.04. Also, need to update the line that says `10 and newer` and `18.04 and newer` to be consistent with the repo changes.

I think it's best to make things consistent with the [podman docs](https://podman.io/getting-started/installation).

**Comment by mr-c** [comment]
@lsm5 Feel free to take over this PR, thanks!

**Comment by lsm5** [comment]
@mr-c will do, thanks

**Comment by lsm5** [comment]
Closing in favor of https://github.com/containers/skopeo/pull/1117 , which includes @mr-c's commit.

**Pull request closed without merging**
