### PR TITLE
Adds the --override-variant command line flag

### PR DESCRIPTION
**Pull request by JirkaChadima**
This is part of #790 and can be merged only after https://github.com/containers/image/pull/786 or https://github.com/containers/image/pull/753

I'm not sure how dependencies work exactly in Go so I did not test this locally against the patched `containers/image` version, but it should work once that dependency is updated.

### CODE REVIEW

**Comment by rhatdan** [comment]
Man pages?

**Comment by mtrmac** [comment]
ACK to the Skopeo part (but it will need to update c/image to one that actually supports that flag).

**Comment by rhatdan** [comment]
@JirkaChadima @mtrmac @vrothberg Do we still need/want this PR?

**Comment by JirkaChadima** [comment]
> @JirkaChadima @mtrmac @vrothberg Do we still need/want this PR?

I'm fine without it, we have changed the pipeline for other reasons. But I still think it's a valuable addition to skopeo.

**Comment by rhatdan** [comment]
@sujil02  PTAL

**Comment by vrothberg** [comment]
I rebased to retrigger the tests; just to be sure.

**Comment by mtrmac** [comment]
@JirkaChadima Thanks again!

**Pull request merged**
