### PR TITLE
install: make commanbds copy-pasteable

### PR DESCRIPTION
**Pull request by glensc**
make the commands copy-pasteble: double click on a line and copy

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@glensc thanks for the PR.  We keep going back/forth on this type of change across the container projects.  Some people like the ease of the triple-click for cut/pasting, others like to see the command prompt to differentiate between commands that need to be run as root or as a rootless user.  I fall in the camp of preferring the command prompt to be shown.  If others would prefer the cut/paste ease, then the changes you're proposing LGTM.

**Comment by glensc** [comment]
if this were shown on a custom homepage, one could style the `#` vs `$` via CSS presentation layer

**Comment by rhatdan** [comment]
@glensc PRs welcome...

**Comment by glensc** [comment]
@rhatdan? this is a PR!

**Comment by rhatdan** [comment]
PR for custom CSS?

**Comment by glensc** [comment]
@rhatdan these docs are on GitHub. we have no control of their md->html rendering process.

**Comment by rhatdan** [comment]
Ok, I thought you knew something I did not know.

@TomSweeneyRedHat Instead of prefixing commands with `$` or `#` we could just use the command and add sudo when the command needs to be run as root.

That would help user distinguish the two use cases, and would work in cut and paste situations.

**Comment by glensc** [comment]
I like the `sudo` distinction!

**Comment by TomSweeneyRedHat** [comment]
@rhatdan ack.  I'm with @glensc on this one, I'm not much for sudo and pref the command prompt symbols still.  But, you're right, distinguishing with sudo where needed would work too.

@glensc looks like you need a rebase on this one.

**Comment by glensc** [comment]
rebasing, but the allow edits is on, so maintainers can rebase themselves if they turned on the linear merge option and making contributions difficult requiring to rebase after each merge

image

**Comment by rhatdan** [comment]
@glensc Needs a rebase.

**Comment by glensc** [comment]
@rhatdan 

rebasing, but the allow edits is on, so maintainers can rebase themselves if they turned on the linear merge option and making contributions difficult requiring to rebase after each merge

image

**Comment by rhatdan** [comment]
LGTM

**Pull request closed without merging**
