### PR TITLE
Update to Go 1.22

### PR DESCRIPTION
**Pull request by mtrmac**
Cc: @Luap99 

@lsm5 PTAL — marking as draft to let you review, to make sure this is not a problem for downstream.

### CODE REVIEW

**Comment by Luap99** [comment]
You will need something like https://github.com/containers/podman/pull/23840/commits/54b8c4fb64e9d362eeb434999735c2e99944f555 to fix the packit config to no longer build in envs with go 1.21

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by lsm5 — APPROVED** [review]
LGTM

Not a problem for downstream. We'll simply end up not updating f39 which will be going EOL in maybe a couple of months.

**Comment by mtrmac** [comment]
Thanks! Ready for merging, then.

**Pull request merged**
