### PR TITLE
[DO NOT MERGE] c/image commit 0cc0e9 + openssl support

### PR DESCRIPTION
**Pull request by lsm5**
go mod edit -replace github.com/containers/image=github.com/lsm5/containers-image@openssl-testing
make vendor

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by lsm5** [comment]
https://github.com/lsm5/containers-image/commits/openssl-testing is the c/image replacement used here.

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
timed out on the last few tests, looking into it...

**Comment by lsm5** [comment]
@vrothberg @mtrmac so things look good now. c/image master branch isn't good to be vendored into skopeo as-is, so that's why vendoring c/libtrust into c/image master failed as well.

I'm hoping we can branch off c/image with commit 0cc0e97 and vendor c/libtrust master branch in there for now and have a separate TODO to fix c/image vendoring (maybe CI can ensure every commit is vendor-able?)

/cc @mrunalp @rhatdan

**Comment by lsm5** [comment]
See https://github.com/containers/skopeo/pull/727 which vendors c/image master branch. Those are similar to what I observed when vendoring in c/image master branch + c/libtrust patch.

**Comment by vrothberg** [comment]
No idea what's going on. It seems related to go mod changing the dependencies which is not (yet) covered in the c/image CI as it's not using `go mod` for testing the branch/PR.

**Comment by lsm5** [comment]
@mtrmac so, it seems that any c/image commit with go mod in it fails skopeo CI. vendoring `335b34f9ac7d` failed the same way as master, while `713c8d43f997` worked fine  (for linux atleast, not for darwin)

**Comment by vrothberg** [comment]
Trying to get it back into a working state here: https://github.com/containers/image/pull/708

**Comment by mtrmac** [comment]
@lsm5 Assuming this is no longer necessary, please reopen if that’s not the case.

**Pull request closed without merging**
