### PR TITLE
Switched to ubuntu 18.04 (EOL and to old golang)

### PR DESCRIPTION
**Pull request by erkules**
Beside 17.10 is EOL.
The golang version shipped with 17.10 wont compile:

~~~
vendor/golang.org/x/net/http2/server.go:220: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)
~~~

Fixed when using ubuntu: 18.04

### CODE REVIEW

**Comment by vrothberg** [comment]
@erkules, thanks for the PR. Could you sign your commit (e.g., `git commit --amend -s`) and then re-push? The change itself LGTM.

@runcom @rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
Change LGTM once signed.

**Comment by rhatdan** [comment]
@erkules Could you merge your three PR's into one and force push.

**Comment by eramoto** [comment]
I verified this PR, or ubuntu 18.10, was able to fix the issue #587

**Comment by vrothberg** [comment]
@erkules, would you rebase the commit? Sorry for the late reply. This PR slipped through.

**Comment by giuseppe** [comment]
@erkules, these two commands you'll get just one patch with `Signed-off-by` on top of master:
```
git pull --rebase origin master
git commit --amend --no-edit -s
```

then you can `git push -f` the result

**Comment by rhatdan** [comment]
If this passes tests will merge.

**Comment by reenberg** [comment]
@rhatdan, @vrothberg, any chance we could skip the git learning curve and any of you could just do this one liner.  It's kind of a shame that it haven't been possible to checkout this repository and building it according to documentation (in a container) since v0.1.32, from Nov 7 2018.  

I respect that you are trying to be helpful and educational.  If it had been something more complex, I could see the reason.  But nothing has really happened the past 3-4 months and it is kind of a stopper.  I wasted way to much time trying to figure out why, as a newcomer to go, before i found the issue / pr describing it.

**Comment by mtrmac** [comment]
LGTM, though a rebase to get rid of 6 extra commits, and notably the old one without a `Signed-Off-By`, would be nice.

**Comment by rhatdan** [comment]
Dockerfile.build is now at FROM ubuntu:18.10
So closing.

**Pull request closed without merging**
