### PR TITLE
Release Skopeo 0.1.37

### PR DESCRIPTION
**Pull request by mtrmac**

### CODE REVIEW

**Comment by mtrmac** [comment]
Note: There is outstanding https://github.com/containers/skopeo/pull/655 ; does that need to be finished first?

**Comment by rhatdan** [comment]
Yes lets get containers/storage and containers/buildah updated first.  We should be able to update buildah today.

**Comment by mtrmac** [comment]
> Yes lets get containers/storage and containers/buildah updated first.

#679

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
