### PR TITLE
Bump to v1.2.2

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by mtrmac** [comment]
@rhatdan Is there something specific you want included in the release? AFAICS the c/common update is just a renaming cleanup. Is that to align versions with other components, or for some other reason?

(Also, there should be a post-release bump to 1.2.3-dev.)

**Comment by rhatdan** [comment]
Yes for the realignment, no other reason.

**Comment by mtrmac** [comment]
OK, so please add a post-release bump, and we’ll include this on both `master` and `release-1.2` branches.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
This is not needed so closing.

**Pull request closed without merging**
