### PR TITLE
Fix storage.conf overrides in test-system in CI, update c/storage

### PR DESCRIPTION
**Pull request by mtrmac**
<s>A wild guess at what is happening in #1863 .</s> See below.

### CODE REVIEW

**Comment by mtrmac** [comment]
This
- Fixes how `make test-system` unnecessarily overrides `storage.conf` in CI.
- Attempts to fix, apparently long-unused, `make test-integration` and `make test-system` running in containers, for developers’ on-workstation use. At least it fixes the failure in #1222, but I didn’t yet actually get this _working_. But apparently it’s not being used, so that’s not nearly as important as the CI.
- Updates c/storage to 1.45.3, the version that is failing without the changes, as a demonstration.

@rhatdan PTAL.

@cevich FYI (non-urgent), this points at a part of the reason of the recent Podman trouble - changing `storage.conf` under a pre-existing Podman database seems to make it unhappy. Now that we don’t do that, that workaround is no longer necessary.

**Comment by mtrmac** [comment]
> Attempts to fix, apparently long-unused, `make test-integration` and `make test-system` running in containers, for developers’ on-workstation use.

This does fix `make test-integration`. `make test-system` does not work for me — there is no reported error, something about the Podman-in-Podman networking seems to just hang when connecting to the registry container. I didn’t investigate that further.

**Review by rhatdan — APPROVED** [review]
LGTM
@vrothberg PTAL

**Review by vrothberg — APPROVED** [review]
/lgtm

**Comment by cevich** [comment]
> @cevich FYI (non-urgent), this points at a part of the reason of the recent Podman trouble - changing storage.conf under a pre-existing Podman database seems to make it unhappy. Now that we don’t do that, that workaround is no longer necessary.

Oh wow, and so you got rid of the "magic" workaround too, fantastic!  Thanks!

**Pull request merged**
