### PR TITLE
[release-1.13] Backport #2280

### PR DESCRIPTION
**Pull request by mtrmac**
This branch is used by the c/image `release-5.26` branch.

### CODE REVIEW

**Comment by mtrmac** [comment]
Merging without review to remove noise from daily CI runs.

**Comment by lsm5** [comment]
@mtrmac checked with the packit folks. This occurred because the branch was changed from `main` to `release-1.13` after PR creation. I've filed an issue with them which has been linked in this PR too. So, I'd say we leave things as they are for now.

**Comment by mtrmac** [comment]
@lsm5 Thanks!

**Comment by lsm5** [comment]
@mtrmac i'm unable to reproduce this issue on https://github.com/containers/skopeo/pull/2298 . So, I wonder if this is a corner case.
-  Do you remember if you changed the target branch from `main` to `release-1.13` right after you created the PR and before the builds completed (regardless of completion status).
- Did you try rerunning the packit jobs after you changed the branch?

**Comment by mtrmac** [comment]
@lsm5 the tooltips on “last week” for filing the PR and changing the branch are both 7:51, so that must have been an ~immediate edit (and that matches what I would expect to happen, as soon as I noticed the large diff I would retarget).

I really can’t remember whether I triggered a restart of the Packit jobs, I’m afraid.

**Comment by lsm5** [comment]
> @lsm5 the tooltips on “last week” for filing the PR and changing the branch are both …:51, so that must have been an ~immediate edit (and that matches what I would expect to happen, as soon as I noticed the large diff I would retarget).

ah yes, I should've checked tooltips before asking :| , anyway thanks for confirming.
> 
> I really can’t remember whether I triggered a restart of the Packit jobs, I’m afraid.

No worries at all. Thanks for the info. I'll look further with the packit team, but hopefully this issue won't be regular occurrence.

**Pull request merged**
