### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Tests are not hip @hswong3i

**Comment by vrothberg** [comment]
Failures are unrelated: see https://github.com/containers/skopeo/issues/1093

**Comment by rhatdan** [comment]
@vrothberg Are you able to restart tests?  I can't and can't figure out why? Any ideas?

**Comment by vrothberg** [comment]
It needs a rebase to pass

**Comment by hswong3i** [comment]
As mentioned at https://github.com/containers/skopeo/pull/1099#issuecomment-726011587 the use of existing `LDFLAG` in `nix/default.nix` is still valid, and my manually local `nix build -f nix/` working as expected.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
