### PR TITLE
copy: add support for `--format zstd`

### PR DESCRIPTION
**Pull request by flouthoc**
`skopeo copy --format zstd` copy contents of manifest list from source to destination and verifying the destination is converted to `OCI` manifest list and each image converted and compression with `zstd` compression algorithm.

Needs: https://github.com/containers/image/pull/2047

### CODE REVIEW

**Comment by mtrmac** [comment]
> Why mix the manifest format and compression algorithm options? Was it perhaps some example where I said `--format zstd`? If so, I apologize.

I did, in https://github.com/containers/image/pull/1987 . I apologize again.

**Comment by flouthoc** [comment]
No Issues, I will amend this to incorporate `--dest-compress-format`

**Comment by mtrmac** [comment]
`--dest-compress-format` already exists, although full text search might not find the implementation: https://github.com/containers/skopeo/blob/38650252d51d626ef16f3b1c30fb50760fd0d499/cmd/skopeo/utils.go#L269 .

**Comment by flouthoc** [comment]
Not needed.

**Pull request closed without merging**
